color0       #000108
color8       #AC9A64
color1       #1D394F
color9       #1D394F
color2       #4A473F
color10      #4A473F
color3       #7F5A3B
color11      #7F5A3B
color4       #997E3B
color12      #997E3B
color5       #E38F39
color13      #E38F39
color6       #FDCA2F
color14      #FDCA2F
color7       #F6DC8E
color15      #F6DC8E