color0       #4C4D50
color8       #948F8D
color1       #1B829C
color9       #1B829C
color2       #74854A
color10      #74854A
color3       #7E7E8B
color11      #7E7E8B
color4       #A98E5F
color12      #A98E5F
color5       #819C9D
color13      #819C9D
color6       #B8ABA4
color14      #B8ABA4
color7       #D3CDC9
color15      #D3CDC9