input {
    kb_layout = us
    numlock_by_default =true 
    repeat_delay = 250
    repeat_rate = 35
    kb_options = scroll:nop
    focus_on_close = 1

    touchpad {
        natural_scroll = true
        disable_while_typing = $touchpadDisableTyping
        scroll_factor = $touchpadScrollFactor
    }
}

binds {
    scroll_event_delay = 0
}

cursor {
    hotspot_padding = 1
}

